import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthRedirect from "@/lib/AuthRedirect";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Area",
  description: "Generated by eq with love",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  bg-white text-black`}>
        <AuthRedirect>{children}</AuthRedirect>
      </body>
    </html>
  );
}
